/* Created By: Alex Cadigan (https://github.com/AlexCadigan) */
function displayHelpPage() { window.location.href = "HelpPage/HelpPage.html"; }
function displayFeedbackPage() { window.location.href = "FeedbackPage/FeedbackPage.html"; }
function displayModule1() { window.location.href = "http://videoclick.epizy.com/#/security"; }
function displayModule2() { window.location.href = "http://videoclick.epizy.com/#/security"; }
function displayModule2_1() { window.location.href = "http://videoclick.epizy.com/#/security"; }
function displayModule2_2() { window.location.href = "http://videoclick.epizy.com/#/security"; }
function displayModule2_3() { window.location.href = "Module2_3/Module2_3.html"; }
function displayModule3() { window.location.href = "Module3/Module3.html"; }
